### ISSUE TITLE
Simplify s3 bucket variables

### ISSUE THREAD

**Issue by eads** [nprapps/app-template#562]

**Comment by livlab** [comment]
original ticket: do we still need to specify region with new s3 deployment routines? 
Answer: No.

So we're cleaning up the bucket paths.

**Comment by benlk** [comment]
Future readers:

If you, like me, ran across this ticket while searching for a solution to a `301` or certificate mismatch error because you have `.` dots in your non-`us-east-1` bucket name, here's a working solution: https://github.com/INN/maine-legislature/commit/5aef6497b291255d67f602dced98412023a2c299
